- hosts: webservers
  vars:
    hello_messages:
        - "world"
        - "web"
  roles:
    - common

- hosts: appservers
  vars:
    hello_messages:
        - "world"
        - "app"
  roles:
    - common
