- hosts: all
  vars:
    to_do_list:
        - develop
        - test
        - deploy
        - take over world
    hello_messages:
        - "world"
        - "wow"
  tasks:
    - name: print meaningless text
      template:
        dest: "~/hello.txt"
        src: "templates/hello.txt.j2"
