---
dependencies: []

galaxy_info:
  author: lesmyrmidons
  description: MongoDB for RedHat/CentOS/Debian 64Bit.
  company: "ARBOUIN Consulting"
  issue_tracker_url: https://github.com/lesmyrmidons/ansible-role-mongodb/issues
  license: "license (BSD, MIT)"
  min_ansible_version: 2.1
  platforms:
  - name: EL
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: RedHat
    versions:
    - all
  categories:
    - database:nosql
